# Generated by Django 2.0.3 on 2018-03-17 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('name', models.CharField(max_length=100)),
                ('player_number', models.IntegerField()),
                ('preferred_foot', models.CharField(choices=[('l', 'LEFT'), ('r', 'RIGHT'), ('b', 'BOTH')], max_length=1)),
                ('natiolity', models.CharField(choices=[('id', 'INDONESIA')], max_length=3)),
                ('injury', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'C')], max_length=1)),
                ('balance', models.IntegerField()),
                ('stamina', models.IntegerField()),
                ('passing', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('dribling', models.IntegerField()),
                ('ability', models.IntegerField()),
                ('defend', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.Club')),
            ],
        ),
    ]
