# Generated by Django 2.0.3 on 2018-03-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20180317_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position_code',
            field=models.CharField(choices=[('cf', 'CF'), ('mf', 'MF'), ('cb', 'CB')], default=' ', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
