# Generated by Django 2.0.3 on 2018-03-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180318_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='founded_year',
            field=models.IntegerField(default=2018, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='natiolity',
            field=models.CharField(choices=[('id', 'INDONESIA')], default='id', max_length=5),
            preserve_default=False,
        ),
    ]
