# Generated by Django 2.0.3 on 2018-03-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='total_goals',
        ),
    ]
