# Generated by Django 2.0.3 on 2018-03-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_match_total_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdetail',
            name='match',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Match'),
            preserve_default=False,
        ),
    ]
