# Generated by Django 2.0.3 on 2018-03-17 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_matchdetail_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetail',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_details', to='event.Match'),
        ),
    ]
