# Generated by Django 2.0.3 on 2018-03-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180317_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdetail',
            name='team',
        ),
    ]
