# Generated by Django 2.0.3 on 2018-03-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_remove_matchdetail_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdetail',
            name='type',
            field=models.CharField(choices=[('goal', 'GOAL'), ('own_goal', 'OWN GOAL'), ('assist', 'ASSIT'), ('red_card', 'RED CARD'), ('yellow_card', 'YELLOW CARD'), ('penalty_success', 'PENALTY SUCCESS'), ('penalty_failed', 'PENALTY FAILED')], max_length=50),
        ),
    ]
